/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleUsuario;
import java.awt.Label;
import java.awt.TextField;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSeparator;



/**
 *
 * @author gabri
 */
public class Cadastro extends javax.swing.JFrame {
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

    public ControleUsuario getC() {
        return c;
    }

    public void setC(ControleUsuario c) {
        this.c = c;
    }

    public JButton getBt_salvar() {
        return bt_salvar;
    }

    public void setBt_salvar(JButton bt_salvar) {
        this.bt_salvar = bt_salvar;
    }

    public JButton getBt_voltar() {
        return bt_voltar;
    }

    public void setBt_voltar(JButton bt_voltar) {
        this.bt_voltar = bt_voltar;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLbl_frut() {
        return lbl_frut;
    }

    public void setLbl_frut(JLabel lbl_frut) {
        this.lbl_frut = lbl_frut;
    }

    public JLabel getLbl_nome() {
        return lbl_nome;
    }

    public void setLbl_nome(JLabel lbl_nome) {
        this.lbl_nome = lbl_nome;
    }

    public JLabel getLbl_senha() {
        return lbl_senha;
    }

    public void setLbl_senha(JLabel lbl_senha) {
        this.lbl_senha = lbl_senha;
    }

    public JLabel getLbl_usuario1() {
        return lbl_usuario1;
    }

    public void setLbl_usuario1(JLabel lbl_usuario1) {
        this.lbl_usuario1 = lbl_usuario1;
    }

    public TextField getTxt_nome() {
        return txt_nome;
    }

    public void setTxt_nome(TextField txt_nome) {
        this.txt_nome = txt_nome;
    }

    public TextField getTxt_senha() {
        return txt_senha;
    }

    public void setTxt_senha(TextField txt_senha) {
        this.txt_senha = txt_senha;
    }

    public TextField getTxt_usuario() {
        return txt_usuario;
    }

    public void setTxt_usuario(TextField txt_usuario) {
        this.txt_usuario = txt_usuario;
    }

 
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nome = new java.awt.TextField();
        txt_usuario = new java.awt.TextField();
        txt_senha = new java.awt.TextField();
        bt_salvar = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        lbl_nome = new javax.swing.JLabel();
        lbl_senha = new javax.swing.JLabel();
        lbl_usuario1 = new javax.swing.JLabel();
        lbl_frut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 143, 100, -1));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 189, 100, -1));
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 245, 100, -1));

        bt_salvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_salvar.setText("Salvar");
        bt_salvar.setContentAreaFilled(false);
        bt_salvar.addActionListener(this::bt_salvarActionPerformed);
        getContentPane().add(bt_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        bt_voltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_voltar.setText("Voltar");
        bt_voltar.setContentAreaFilled(false);
        bt_voltar.addActionListener(this::bt_voltarActionPerformed);
        getContentPane().add(bt_voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        lbl_nome.setBackground(new java.awt.Color(242, 151, 65));
        lbl_nome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_nome.setText("Nome");
        getContentPane().add(lbl_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_senha.setText("Senha");
        getContentPane().add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lbl_usuario1.setBackground(new java.awt.Color(242, 151, 65));
        lbl_usuario1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_usuario1.setText("Usuário");
        getContentPane().add(lbl_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        lbl_frut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Gemini_Generated_Image_53onjh53onjh53on.png"))); // NOI18N
        lbl_frut.setOpaque(true);
        getContentPane().add(lbl_frut, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -10, 670, 560));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
  
    String nome = txt_nome.getText();
    String usuario = txt_usuario.getText();
    String senha = txt_senha.getText(); 

    c.cadastrarUsuario(nome, usuario, senha);
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
       
        this.dispose();
        new TelaLogin().setVisible(true);
        
    }//GEN-LAST:event_bt_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
//    }

    
    ControleUsuario c = new ControleUsuario();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_frut;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario1;
    private java.awt.TextField txt_nome;
    private java.awt.TextField txt_senha;
    private java.awt.TextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
