/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleLogin;
import java.awt.TextField;
import javax.swing.JButton;
import javax.swing.JLabel;
/**
 *
 * @author gabri
 */
public class TelaLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form Login
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controle = new ControleLogin(this);
    }

    public ControleLogin getControle() {
        return controle;
    }

    public void setControle(ControleLogin controle) {
        this.controle = controle;
    }

    public JButton getBt_cadastro() {
        return bt_cadastro;
    }

    public void setBt_cadastro(JButton bt_cadastro) {
        this.bt_cadastro = bt_cadastro;
    }

    public JButton getBt_entrar() {
        return bt_entrar;
    }

    public void setBt_entrar(JButton bt_entrar) {
        this.bt_entrar = bt_entrar;
    }

    public JButton getBtn_sair() {
        return btn_sair;
    }

    public void setBtn_sair(JButton btn_sair) {
        this.btn_sair = btn_sair;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getLbl_senha() {
        return lbl_senha;
    }

    public void setLbl_senha(JLabel lbl_senha) {
        this.lbl_senha = lbl_senha;
    }

    public JLabel getLbl_usuario() {
        return lbl_usuario;
    }

    public void setLbl_usuario(JLabel lbl_usuario) {
        this.lbl_usuario = lbl_usuario;
    }

    public TextField getTxt_senha() {
        return txt_senha;
    }

    public void setTxt_senha(TextField txt_senha) {
        this.txt_senha = txt_senha;
    }

    public TextField getTxt_usuario() {
        return txt_usuario;
    }

    public void setTxt_usuario(TextField txt_usuario) {
        this.txt_usuario = txt_usuario;
    }

  
   

  
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_entrar = new javax.swing.JButton();
        txt_usuario = new java.awt.TextField();
        bt_cadastro = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        txt_senha = new java.awt.TextField();
        lbl_senha = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt_entrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_entrar.setContentAreaFilled(false);
        bt_entrar.addActionListener(this::bt_entrarActionPerformed);
        getContentPane().add(bt_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 110, 20));

        bt_cadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bt_cadastro.setText("Cadastrar");
        bt_cadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cadastro.setContentAreaFilled(false);
        bt_cadastro.addActionListener(this::bt_cadastroActionPerformed);
        getContentPane().add(bt_cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        btn_sair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_sair.setContentAreaFilled(false);
        btn_sair.addActionListener(this::btn_sairActionPerformed);
        getContentPane().add(btn_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 60, -1));

        txt_senha.addActionListener(this::txt_senhaActionPerformed);
        getContentPane().add(txt_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 110, 20));

        lbl_senha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_senha.setText("Senha");
        getContentPane().add(lbl_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        lbl_usuario.setBackground(new java.awt.Color(242, 151, 65));
        lbl_usuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_usuario.setText("Usuário");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-510, -480, 1160, 1220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void bt_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_entrarActionPerformed
        controle.loginUsuarios();
    }//GEN-LAST:event_bt_entrarActionPerformed

    private void bt_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastroActionPerformed
 

       new Cadastro().setVisible(true);
        
    }//GEN-LAST:event_bt_cadastroActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
//    }

   private ControleLogin controle;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastro;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_usuario;
    private java.awt.TextField txt_senha;
    private java.awt.TextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
